### PR TITLE
Basic Resource system implementation

### PR DESCRIPTION
**Pull request by woksin**
Lacking Specs.

We can use Dolittle.Resources.ICanDefineAResource to define resource type => name => configuration mapping instead of using IRepresentAResourceType perhaps?

A resource definition could then be:
```csharp
public class MongoReadModelsResourceDefinition : ICanDefineAResource
{
    public ResourceType ResourceType => "readModels";
    public ResourceTypeName ResourceTypeName => "MongoDB";
    public Type ConfigurationObjectType => typeof(MongoReadModelsConfiguration);
}
```
for example. And the MongoReadModelsConfiguration could look like this:
```csharp
 public class MongoReadModelsConfiguration
{
        public string ConnectionString {get; set;}
}
```

### CODE REVIEW

**Comment by einari** [comment]
Do you want me to wait on review with regards to the changes we discussed in #97 ?

**Comment by woksin** [comment]
Perhaps that's the best, doesn't really matter for me, I have to implement it either way 😄

**Comment by einari** [comment]
I guess this is work in progress. 
Had a few comments related to the bindings. 

I see you've started on Specs, so lets keep this open till those are in place :)

**Comment by smithmx** [comment]
Just had a quick read over this - and not privy to the discussions you have had - but it looks fine.

The only thing I would like is to sit something on top of it to make it more strongly typed.  So a ReadModel resource type, an EventStore resource type.  We can then extend these within the particular implementations so that we can have a MongoDB resource config in ReadModels.MongoDB that hides all the resource stuff and only focuses on the Mongo specific stuff.  Likewise with Azure.

I think this is more "nice to have" than essential though.

**Comment by woksin** [comment]
@smithmx I think that what you're asking for is implemented in the Runtime.
See https://github.com/dolittle/Runtime/pull/91/files

**Comment by einari** [comment]
Great job on the implementation here - for the specs, I don't like seeing the ReadModel, EventStore, Geodesics and MongoDB and Azure things at this level. You should keep them as the scenarios you're testing. For instance, ResourceTypeWithOneService, ResourceTypeWithMultipleServices and such. It is not the fact that you are talking read models or event stores, but the scenarios the system is supporting. Make the scenarios explicit. Other than that, great work!   I'll wait to pull this till you have this done.

**Comment by einari** [comment]
Nice.   Looking good and much clearer. Just a couple of comments on consistency around naming - remember that Specs should be read out in English, don't think about types and technical building blocks. Look at it as something that should explain how the system should work - its a specification.

**Pull request merged**
